name: Docs 📚

on:
  push:
    branches:
      - main

jobs:
  docs:
    name: Pkgdown Docs 📚
    uses: phuse-org/devops-toolkit/.github/workflows/pkgdown.yml@main
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
